from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(710, 341)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gateway = QtWidgets.QLabel(self.centralwidget)
        self.gateway.setGeometry(QtCore.QRect(20, 200, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.gateway.setFont(font)
        self.gateway.setStyleSheet("color: rgb(21, 68, 127);")
        self.gateway.setObjectName("gateway")
        self.subnet = QtWidgets.QLabel(self.centralwidget)
        self.subnet.setGeometry(QtCore.QRect(20, 140, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.subnet.setFont(font)
        self.subnet.setStyleSheet("color: rgb(21, 68, 127);")
        self.subnet.setObjectName("subnet")
        self.connect_btn = QtWidgets.QPushButton(self.centralwidget)
        self.connect_btn.setGeometry(QtCore.QRect(500, 260, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.connect_btn.setFont(font)
        self.connect_btn.setStyleSheet("background-color: rgb(21, 68, 127);\n"
"color: rgb(255, 255, 255);")
        self.connect_btn.setObjectName("connect_btn")
        self.ipLabel = QtWidgets.QLabel(self.centralwidget)
        self.ipLabel.setGeometry(QtCore.QRect(400, 80, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ipLabel.setFont(font)
        self.ipLabel.setStyleSheet("color: rgb(21, 68, 127);")
        self.ipLabel.setObjectName("ipLabel")
        self.send_btn = QtWidgets.QPushButton(self.centralwidget)
        self.send_btn.setGeometry(QtCore.QRect(120, 260, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.send_btn.setFont(font)
        self.send_btn.setStyleSheet("background-color: rgb(21, 68, 127);\n"
"color: rgb(255, 255, 255);")
        self.send_btn.setObjectName("send_btn")
        self.ip = QtWidgets.QLabel(self.centralwidget)
        self.ip.setGeometry(QtCore.QRect(20, 80, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ip.setFont(font)
        self.ip.setStyleSheet("color: rgb(21, 68, 127);")
        self.ip.setObjectName("ip")
        self.hostname = QtWidgets.QLabel(self.centralwidget)
        self.hostname.setGeometry(QtCore.QRect(20, 20, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.hostname.setFont(font)
        self.hostname.setStyleSheet("color: rgb(21, 68, 127);")
        self.hostname.setObjectName("hostname")
        self.passLabel = QtWidgets.QLabel(self.centralwidget)
        self.passLabel.setGeometry(QtCore.QRect(400, 200, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.passLabel.setFont(font)
        self.passLabel.setStyleSheet("color: rgb(21, 68, 127);")
        self.passLabel.setObjectName("passLabel")
        self.userLabel = QtWidgets.QLabel(self.centralwidget)
        self.userLabel.setGeometry(QtCore.QRect(400, 140, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.userLabel.setFont(font)
        self.userLabel.setStyleSheet("color: rgb(21, 68, 127);")
        self.userLabel.setObjectName("userLabel")
        self.hostname_3 = QtWidgets.QLabel(self.centralwidget)
        self.hostname_3.setGeometry(QtCore.QRect(400, 20, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.hostname_3.setFont(font)
        self.hostname_3.setStyleSheet("color: rgb(21, 68, 127);")
        self.hostname_3.setObjectName("hostname_3")
        self.hostn_text = QtWidgets.QLineEdit(self.centralwidget)
        self.hostn_text.setGeometry(QtCore.QRect(170, 19, 141, 31))
        self.hostn_text.setObjectName("hostn_text")
        self.ip_text = QtWidgets.QLineEdit(self.centralwidget)
        self.ip_text.setGeometry(QtCore.QRect(170, 80, 141, 31))
        self.ip_text.setObjectName("ip_text")
        self.subnet_text = QtWidgets.QLineEdit(self.centralwidget)
        self.subnet_text.setGeometry(QtCore.QRect(170, 140, 141, 31))
        self.subnet_text.setObjectName("subnet_text")
        self.gateway_text = QtWidgets.QLineEdit(self.centralwidget)
        self.gateway_text.setGeometry(QtCore.QRect(170, 200, 141, 31))
        self.gateway_text.setObjectName("gateway_text")
        self.ssh_user = QtWidgets.QLineEdit(self.centralwidget)
        self.ssh_user.setGeometry(QtCore.QRect(550, 140, 141, 31))
        self.ssh_user.setObjectName("ssh_user")
        self.ssh_pass = QtWidgets.QLineEdit(self.centralwidget)
        self.ssh_pass.setGeometry(QtCore.QRect(550, 200, 141, 31))
        self.ssh_pass.setObjectName("ssh_pass")
        self.ssh_ip = QtWidgets.QLineEdit(self.centralwidget)
        self.ssh_ip.setGeometry(QtCore.QRect(550, 80, 141, 31))
        self.ssh_ip.setObjectName("ssh_ip")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 710, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gateway.setText(_translate("MainWindow", "Gateway :"))
        self.subnet.setText(_translate("MainWindow", "Subnet :"))
        self.connect_btn.setText(_translate("MainWindow", "Connect"))
        self.ipLabel.setText(_translate("MainWindow", "IP : "))
        self.send_btn.setText(_translate("MainWindow", "Send"))
        self.ip.setText(_translate("MainWindow", "Ip :"))
        self.hostname.setText(_translate("MainWindow", "Host Name : "))
        self.passLabel.setText(_translate("MainWindow", "Password :"))
        self.userLabel.setText(_translate("MainWindow", "User :"))
        self.hostname_3.setText(_translate("MainWindow", "SSH Connection : "))
