# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DesignMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
# from SSHConnect import SSH_operation
from PyQt5.QtWidgets import QMainWindow, QApplication
import sys
from design import Ui_MainWindow

class AppWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        self.ui.connect_btn.clicked.connect(self.ConnectButtonClicked)
        self.show()



    @staticmethod
    def ConnectButtonClicked(self, ipaddr):




# ssh_obj = SSH_operation()
# ssh_obj.ssh_con("10.1.3.75", "ezgi", "0000")
# ssh_obj.ssh_command("pwd")


app = QApplication(sys.argv)
w = AppWindow()
w.show()
sys.exit(app.exec_())